# Generated by Django 5.2.16 on 2026-07-26 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('target_url', models.URLField(max_length=500, verbose_name='target URL')),
                ('pages_discovered', models.PositiveIntegerField(default=0, verbose_name='pages discovered')),
                ('pages_scanned', models.PositiveIntegerField(default=0, verbose_name='pages scanned')),
                ('contacts_found', models.PositiveIntegerField(default=0, verbose_name='contacts found')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('task_id', models.CharField(blank=True, help_text='Empty when the scan ran inline rather than on a worker.', max_length=255, verbose_name='Celery task id')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='companies.company', verbose_name='company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('careers', 'Careers'), ('jobs', 'Jobs'), ('contact', 'Contact'), ('team', 'Team'), ('leadership', 'Leadership'), ('press', 'Press'), ('other', 'Other')], default='other', max_length=20, verbose_name='page type')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='title')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('emails_found', models.PositiveIntegerField(default=0, verbose_name='emails found')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='fetched at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='companies.company', verbose_name='company')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.scan', verbose_name='scan')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user', '-created_at'], name='scan_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['company', '-created_at'], name='scan_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='scan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['company', '-created_at'], name='page_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['scan', 'page_type'], name='page_scan_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('scan', 'url'), name='unique_page_url_per_scan'),
        ),
    ]
