# Generated by Django 5.2.16 on 2026-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set when a user asks to stop a scan that is already running.', verbose_name='cancellation requested'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
    ]
