# Generated by Django 5.2.16 on 2026-07-26 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('classification', models.CharField(choices=[('hr', 'HR'), ('recruitment', 'Recruitment'), ('careers', 'Careers'), ('talent', 'Talent'), ('jobs', 'Jobs'), ('support', 'Support'), ('sales', 'Sales'), ('media', 'Media'), ('general', 'General'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='classification')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='source page URL')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_favourite', models.BooleanField(db_index=True, default=False, verbose_name='favourite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
