# Generated by Django 5.2.16 on 2026-07-26 03:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('website', models.URLField(help_text="Normalised on save, e.g. 'Example.com/' becomes 'https://example.com'.", max_length=500, verbose_name='website URL')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='industry')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='country')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Free-text notes stored on the company record itself.', verbose_name='notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='companies.company', verbose_name='company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', '-created_at'], name='company_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'industry'], name='company_user_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'country'], name='company_user_country_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_company_name_per_user', violation_error_message='You have already added a company with this name.'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='note_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['company', '-created_at'], name='note_company_recent_idx'),
        ),
    ]
