# Generated by Django 5.2.16 on 2026-07-26 04:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('position', models.CharField(max_length=255, verbose_name='position applied for')),
                ('application_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='application date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('waiting', 'Waiting'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.company', verbose_name='company')),
                ('contact', models.ForeignKey(blank=True, help_text='The discovered contact this was sent to, when there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='contacts.contact', verbose_name='contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-application_date', '-created_at', 'id'],
                'indexes': [models.Index(fields=['user', '-application_date'], name='application_user_date_idx'), models.Index(fields=['user', 'status'], name='application_user_status_idx'), models.Index(fields=['company', '-created_at'], name='application_company_idx')],
            },
        ),
    ]
