apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: job-outreach
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: haze21/job-outreach-backend:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets